# Generated by Django 2.2.17 on 2021-03-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
