# Generated by Django 2.2.17 on 2021-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditoapp', '0002_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('student', 'STUDENT')], default='teacher', max_length=10),
        ),
    ]
