# Generated by Django 2.2.17 on 2021-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditoapp', '0003_auto_20210402_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='Default.jpg', upload_to='profile_images'),
        ),
    ]
