# Generated by Django 2.2.17 on 2021-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditoapp', '0005_usefulresource_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='Default.jpg', upload_to='profile_images'),
        ),
    ]
