# Generated by Django 2.2.17 on 2021-04-03 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eruditoapp', '0006_auto_20210402_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ManyToManyField(to='eruditoapp.Comment'),
        ),
        migrations.CreateModel(
            name='ThreadVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ManyToManyField(to='eruditoapp.Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
